apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
  template:
    metadata:
      labels:
        svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
        ports:
          - containerPort: {{.Values.service.targetPort}}
        env:
          - name: WORLD
            valueFrom:
              configMapKeyRef:
                key: de
                name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
  template:
    metadata:
      labels:
        svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
        ports:
          - containerPort: {{.Values.service.targetPort}}
        env:
          - name: WORLD
            valueFrom:
              configMapKeyRef:
                key: fr
                name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es
  template:
    metadata:
      labels:
        svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
        ports:
          - containerPort: {{.Values.service.targetPort}}
        env:
          - name: WORLD
            valueFrom:
              configMapKeyRef:
                key: es
                name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}
