apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
  labels:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    name: http
  selector:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-de
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
  labels:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    name: http
  selector:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-fr
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es
  labels:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    name: http
  selector:
    svc-name: {{ .Values.image.name }}-{{.Values.deployment.depRegion}}-es