apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logs-admin
rules:
- apiGroups: ["*"] # This was the change
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logs-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: logs-admin
  apiGroup: rbac.authorization.k8s.io
